#!/bin/bash

metagenomes="PAzules PAzules2 PAzules3"

# The next loop will read the content of compressed metagenomic data previously generated by the user and use metaphlan script to predict otus content.
# Note that you should have had installed metaphlan2 and saved your compressed data inside data folder (for more information, go back to README file).

for s in ${metagenomes};
do
	tar -xjf ../data/${s}.tar.bz2 --to-stdout | python ../metaphlan2/metaphlan2.py --input_type multifastq --bowtie2out ../predict_otus/BWT${s}.bt2out > ../predict_otus/${s}.txt;

done
